var blockNames = [
	"NONE",
	"GRASS",
	"SAND",
	"WOOL",
	"FIRE",
	"ICE",
	"METAL",
	"PLANT",
	"SNOW",
	"CLAY",
	"DIRT",
	"STONE",
	"WATER",
	"WOOD",
	"QUARTZ",
	"COLOR_ORANGE",
	"COLOR_MAGENTA",
	"COLOR_LIGHT_BLUE",
	"COLOR_YELLOW",
	"COLOR_LIGHT_GREEN",
	"COLOR_PINK",
	"COLOR_GRAY",
	"COLOR_LIGHT_GRAY",
	"COLOR_CYAN",
	"COLOR_PURPLE",
	"COLOR_BLUE",
	"COLOR_BROWN",
	"COLOR_GREEN",
	"COLOR_RED",
	"COLOR_BLACK",
	"GOLD",
	"DIAMOND",
	"LAPIS",
	"EMERALD",
	"PODZOL",
	"NETHER",
	"TERRACOTTA_WHITE",
	"TERRACOTTA_ORANGE",
	"TERRACOTTA_MAGENTA",
	"TERRACOTTA_LIGHT_BLUE",
	"TERRACOTTA_YELLOW",
	"TERRACOTTA_LIGHT_GREEN",
	"TERRACOTTA_PINK",
	"TERRACOTTA_GRAY",
	"TERRACOTTA_LIGHT_GRAY",
	"TERRACOTTA_CYAN",
	"TERRACOTTA_PURPLE",
	"TERRACOTTA_BLUE",
	"TERRACOTTA_BROWN",
	"TERRACOTTA_GREEN",
	"TERRACOTTA_RED",
	"TERRACOTTA_BLACK",
	"CRIMSON_NYLIUM",
	"CRIMSON_STEM",
	"CRIMSON_HYPHAE",
	"WARPED_NYLIUM",
	"WARPED_STEM",
	"WARPED_HYPHAE",
	"WARPED_WART_BLOCK"
]

var blockDetails = [
	"Transparent",
	"Grass Block, Slime Block",
	"Sand, Birch planks",
	"Cobweb, Mushroom Stem",
	"Lava, TNT, Fire, Redstone Block",
	"Ice",
	"Grindstone, Block of Iron, Iron Door, Iron Preassure Plate, Iron Trapdoor",
	"Leaves",
	"Snow, Wool, Carpet",
	"Clay",
	"Dirt",
	"Stone",
	"Water",
	"Oak (Planks, Preassure Plate)",
	"Diorite, Birch Log, Quartz Block",
	"Orange Wool",
	"Magenta Wool",
	"Light Blue Wool",
	"Yellow Wool",
	"Lime Wool",
	"Pink Wool",
	"Gray Wool",
	"Light Gray Wool",
	"Cyan Wool",
	"Purple Wool",
	"Blue Wool",
	"Brown Wool",
	"Green Wool",
	"Red Wool",
	"Black Wool",
	"Block of Gold, Gold Preassure Plate",
	"Block of Diamond, Prismarine Bricks",
	"Lapis Lazuli Block",
	"Block of Emerald",
	"Podzol, Spruce (Planks)",
	"Netherrack",
	"White Terracotta",
	"Orange Terracotta",
	"Magenta Terracotta",
	"Light Blue Terracotta",
	"Yellow Terracotta",
	"Lime Terracotta",
	"Pink Terracotta",
	"Gray Terracotta",
	"Light Gray Terracotta",
	"Cyan Terracotta",
	"Purple Terracotta",
	"Blue Terracotta",
	"Brown Terracotta",
	"Green Terracotta",
	"Red Terracotta",
	"Black Terracotta",
	"Crimson Nylium",
	"Crimson (Planks)",
	"Crimson (Hyphae)",
	"Warped Nylium",
	"Warped (Planks)",
	"Warped (Hyphae)",
	"Warped Wart Block"
]



